//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instant_Cleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Instant_Cleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exp {
            get {
                object obj = ResourceManager.GetObject("exp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ipconfig /FlushDNS
        ///ping localhost -n 01 &gt;nul
        ///cleanmgr /verylowdisk /d
        ///rd C:\Windows\prefetch /s /q
        ///md C:\Windows\prefetch
        ///exit.
        /// </summary>
        internal static string exp1_bat {
            get {
                return ResourceManager.GetString("exp1.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast {
            get {
                object obj = ResourceManager.GetObject("fast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %windir%\system32\rundll32.exe advapi32.dll,ProcessIdleTasks
        ///exit.
        /// </summary>
        internal static string fast1_bat {
            get {
                return ResourceManager.GetString("fast1.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap min {
            get {
                object obj = ResourceManager.GetObject("min", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to del %temp%\*.* /f /q
        ///exit.
        /// </summary>
        internal static string min1_bat {
            get {
                return ResourceManager.GetString("min1.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rd %temp%
        ///del /f /s /q %systemdrive%\*.tmp
        ///ping localhost -n 01 &gt;nul
        ///del /f /s /q %systemdrive%\*._mp
        ///ping localhost -n 01 &gt;nul
        ///del /f /s /q %systemdrive%\*.log
        ///ping localhost -n 01 &gt;nul
        ///del /f /s /q %systemdrive%\*.gid
        ///ping localhost -n 01 &gt;nul
        ///del /f /s /q %systemdrive%\*.chk
        ///ping localhost -n 01 &gt;nul
        ///del /f /s /q %systemdrive%\*.old
        ///ping localhost -n 01 &gt;nul
        ///del /f /s /q %systemdrive%\recycled\*.*
        ///ping localhost -n 01 &gt;nul
        ///del /f /s /q %windir%\*.bak
        ///ping localhost -n 01 &gt;nul
        ///del /f /s / [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string normal1_bat {
            get {
                return ResourceManager.GetString("normal1.bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spfAnimationFast {
            get {
                object obj = ResourceManager.GetObject("spfAnimationFast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splAnimation {
            get {
                object obj = ResourceManager.GetObject("splAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
